project_name: p2p-bob-exchange
description: p2p-bob-exchange
author: Andres Chirinos
created_date: 2025-05-01
version: 1.0.0

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  folder_id: "1q9XHo4nUIawftnjeLVfSBbEM5r9q3qjn"

kaggle:
  dataset_id: "andreschirinos/p2p-bob-exchange"
  is_public: true
